config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'

  get 'welcome/contact'

  get 'welcome/about'

  root :to => 'welcome#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weclome_helper.rb
module WeclomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rapidcrm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--    Navigation bar -->
  <%= link_to "home", welcome_home_path %>
  <%= link_to "About us", welcome_about_path %>
  <%= link_to "Contact", welcome_contact_path %>


<!--    Navigation bar -->


  <%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Weclome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Weclome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/home.html.erb
<h1>Rapid CRM homepage</h1>
<p>Any contact we want right here..</p>